[1/x] Fix: add `inttoptr` after emitting the address of a global variable
0xPolygonMiden/compiler pull request #179
Opened 2024-05-04 13:27 UTC by greenhat

Otherwise, the subsequent `store`/`load` will fail (expecting a `Ptr`).

2024-05-04 13:31 UTC, greenhat commented on codegen/masm/src/codegen/emitter.rs
> +                emitter.inttoptr(&Type::Ptr(Type::Unknown.into()));
@bitwalker I tried to find the type of the global var, but seems like we're missing it in the `GlobalValueData::Symbol`. 
BTW, why do we return `Ptr(i8)` at https://github.com/0xPolygonMiden/compiler/blob/cc3f74072b2eff7f48b8e31386f8ed4e7820baaa/hir/src/dataflow.rs#L155 for `Symbol`?

2024-05-06 08:07 UTC, bitwalker requested changes
Just one adjustment, but otherwise looks good!

2024-05-06 12:34 UTC, greenhat commented on codegen/masm/src/codegen/emitter.rs
> +                emitter.inttoptr(&Type::Ptr(Type::Unknown.into()));
Got it. Done.

2024-05-07 05:53 UTC, bitwalker approved these changes

2024-05-07 05:53 UTC, merged